# Generated by Django 2.2.5 on 2020-01-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField()),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
                ('seconds', models.PositiveIntegerField()),
                ('to_whom', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Електронное письмо',
                'verbose_name_plural': 'Електронные письма',
            },
        ),
    ]
