# Generated by Django 2.2.5 on 2020-01-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emailer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='datetime_must_be_send',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время отправки'),
        ),
    ]
