# Generated by Django 2.2.5 on 2020-01-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emailer', '0002_auto_20200124_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='message',
            field=models.CharField(max_length=500, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='email',
            name='seconds',
            field=models.PositiveIntegerField(verbose_name='Через сколько секунд отправлять'),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='email',
            name='to_whom',
            field=models.EmailField(max_length=254, verbose_name='Кому отправлять'),
        ),
    ]
