# Generated by Django 2.2.5 on 2020-01-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emailer', '0003_auto_20200124_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='seconds',
            field=models.DateTimeField(verbose_name='Когда отправлять'),
        ),
    ]
